name: Atualizar Avisos (Sheets)

on:
  schedule:
    # O "*/10" significa: "Rode a cada minuto m√∫ltiplo de 10" (00, 10, 20, 30, 40, 50)
    - cron: '*/10 * * * *'
  workflow_dispatch: # Permite rodar manualmente

permissions:
  contents: write

jobs:
  update-sheets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests
      - name: Sincronizar Google Sheets
        run: python update_avisos.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto: Atualizando avisos da Planilha"
          file_pattern: avisos.json